import { AppRegistry } from 'react-native';
import { getStorybookUI, configure } from '@storybook/react-native';
import { name as appName } from '../app.json';
import './storybook.requires'; // This file will be generated by Storybook CLI or a similar process

// Dynamically load stories
configure(() => {
  // Use require.context to load stories dynamically if available and configured,
  // or list them manually. For v6, manual requires are common.
  // This path '../src/stories/index' assumes a central file for requiring stories.
  require('../src/stories/index');
}, module);

const StorybookUIRoot = getStorybookUI({
  // Options for Storybook UI
  onDeviceUI: true, // Enable on-device UI
  //   asyncStorageSupport: true, // Consider adding for persistence if needed
  //   shouldPersistSelection: true, // Persist story selection
});

// If you are using React Native vanilla write this:
AppRegistry.registerComponent(appName, () => StorybookUIRoot);

export default StorybookUIRoot;
