// .storybook/index.js

// Import the getStorybookUI and configure functions from Storybook
import { getStorybookUI, configure } from '@storybook/react-native';
import { name as appName } from '../app.json'; // Ensure you have app.json and it has a name property
import { AppRegistry } from 'react-native';

import './storybook.requires'; // This file will be generated by react-native-storybook-loader

// Import your stories
// While react-native-storybook-loader will auto-generate story loading,
// you might initially need to manually tell configure where your stories are,
// or ensure the loader is set up correctly in subsequent steps.
// For now, we rely on storybook.requires.js to be generated.

// Configure Storybook
// The `configure` function is used to load your stories.
// The first argument is a function that calls `require.context` to load stories dynamically.
// However, with `@storybook/react-native` v6+ and `react-native-storybook-loader`,
// this manual configuration is often handled by the auto-generated `storybook.requires.js`.
// We'll ensure this is set up in the package.json scripts.
configure(() => {
  // require('../src/components/MyComponent.stories.js'); // Example of manual story loading if needed
  // The line below is typically what react-native-storybook-loader would handle.
  // require('./storybook.requires');
}, module);

// Get the Storybook UI
// This is the main UI component for Storybook that you'll render in your app.
const StorybookUIRoot = getStorybookUI({
  // Options for the Storybook UI
  // `asyncStorage` can be null or an AsyncStorage implementation.
  // Null means it won't persist UI changes like selected story/addon.
  // For persistence, you might use `@react-native-async-storage/async-storage`.
  // We'll keep it simple for now.
  asyncStorage: null, // You can use @react-native-async-storage/async-storage for persistence
});

// If you're not using Expo, uncomment the line below
// AppRegistry.registerComponent(appName, () => StorybookUIRoot);

export default StorybookUIRoot;
